const IMPORTED_TASKS = [
  { id: "t1", title: "Raumplan Halle + Keller Kunstwerk Koeln beschaffen", category: "koeln", who: ["Joel Baumann", "Laura Därr"], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Grundriss von Jens anfragen — Masse, Tueren, Steckdosen, Licht" },
  { id: "t2", title: "Raumplan digitalisieren und in Miro uebertragen", category: "koeln", who: ["Leonie"], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t3", title: "Raumplan Brussel Wintergarten (Jan van Damme) anfragen", category: "koeln", who: ["Joel Baumann", "Laura Därr"], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Masse, Licht, Strom" },
  { id: "t4", title: "Raumplan Brussel in Miro teilen", category: "koeln", who: ["Leonie"], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t5", title: "3D-Modell Halle erstellen (Koeln)", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "Tool klaeren: SketchUp / Blender / Matterport — wer macht das?" },
  { id: "t6", title: "3D-Modell Keller erstellen (Koeln)", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t7", title: "3D-Modell Wintergarten CPDP erstellen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t8", title: "Haenge-/Installationsplan Halle erarbeiten (Positionen aller Werke)", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Dringend", notes: "Als Layer im Raumplan / Miro" },
  { id: "t9", title: "Haenge-/Installationsplan Keller erarbeiten", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t10", title: "Lichtplan erstellen (welches Werk braucht welches Licht?)", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "Abstimmen mit Technik und Kunstwerk Koeln" },
  { id: "t11", title: "Stromanschluss-Plan: Welche Werke brauchen Strom / wo?", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t12", title: "Aufbauplanung Koeln: Zeitplan fuer Aufbautage erstellen", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "Reihenfolge und Zeitbedarf pro Werk planen" },
  { id: "t13", title: "Schluessueluebergabe und Zugang klaeren (Keller ab 11., Halle ab 17./18. Mai)", category: "koeln", who: ["Joel Baumann", "Laura Därr"], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Mit Jens / Leon abstimmen" },
  { id: "t14", title: "Brandschutz-Briefing mit Leon / Kunstwerk-Team (blaue Anlage)", category: "koeln", who: ["Joel Baumann", "Laura Därr"], dueDate: "vor Aufbau", status: "Offen", priority: "Dringend", notes: "Pflicht! Evakuierungsplan, Zustaendigkeiten" },
  { id: "t15", title: "Anfrage Werkstaetten KHK: Ausstellungsmodule / Plinthe", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t16", title: "Kurationskonzept ausarbeiten (Centerpiece als Ausgangspunkt)", category: "koeln", who: ["Laura Därr"], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Konzept Centerpiece als Ausgangspunkt — Seminar-Ergebnis vorhanden" },
  { id: "t17", title: "Anfrage Rahel Zaugg Centerpiece Interior", category: "koeln", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t18", title: "Finale Liste: Welche Arbeiten werden in Koeln gezeigt?", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t19", title: "Positionen aller Arbeiten im Raumplan festlegen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Dringend", notes: "Abstimmung mit Raumplan" },
  { id: "t20", title: "Kuration Keller: Programm planen (Talks, Panels, Sit-ins, Filmdreh)", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "Keller ab 11. Mai nutzbar" },
  { id: "t21", title: "Werktexte und Beschriftungen aller Arbeiten erstellen", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "Einheitliches Format festlegen" },
  { id: "t22", title: "Einleitungstext Ausstellung schreiben (Wandtext / Flyer)", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t23", title: "Kurationspositionen anfragen (externe Kuratorin?)", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t24", title: "Tech Rider Koeln erstellen (vollstaendige Technik-Liste)", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "AV, Licht, Strom, Kabel, Haengesysteme..." },
  { id: "t25", title: "Technik ausleihen: Angebote einholen", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t26", title: "Technik ausleihen: Buchung bestaetigen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t27", title: "Leinwaende / Projektoren — Bedarf klaeren und bestellen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t28", title: "Lautsprecher / Audio-Equipment — Bedarf klaeren", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t29", title: "Netzwerk / WLAN in Halle klaeren", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t30", title: "Transporter mieten Koeln (Aufbautage November / Dezember)", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t31", title: "Transport- und Verpackungsplan fuer alle Werke erstellen", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "Welche Kisten / Verpackung braucht was?" },
  { id: "t32", title: "Vernissage 11. Dez. — Konzept und Ablauf planen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Dringend", notes: "Datum: 11. Dezember 2026" },
  { id: "t33", title: "Vernissage: Einladungsliste erstellen", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t34", title: "Vernissage: Einladung designen und versenden", category: "koeln", who: [], dueDate: "November", status: "Offen", priority: "Normal", notes: "3 Wochen vorher versenden — Versand bis 20. Nov." },
  { id: "t35", title: "Vernissage: Catering / Getraenke anfragen (Empfehlung Kunstwerk Koeln)", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t36", title: "Vernissage: Sicherheitsdienst anfragen (Pflicht >50 Personen)", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Dringend", notes: "Blaue Anlage — Aufsicht Pflicht bei oeffentl. Events" },
  { id: "t37", title: "Finissage — Datum festlegen", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Datum noch offen" },
  { id: "t38", title: "Finissage — Konzept und Ablauf planen", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t39", title: "3. Event — intern besprechen und Format festlegen", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Noch nicht definiert — intern klaeren!" },
  { id: "t40", title: "3. Event — Datum festlegen", category: "koeln", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t41", title: "3. Event — Konzept, Einladung, Planung", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t42", title: "Keller-Programm planen: Talks, Panels, Sit-ins", category: "koeln", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "Keller ab 11. Mai nutzbar" },
  { id: "t43", title: "Unterbringung Kuenstler:innen Koeln", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t44", title: "Unterbringung Studierende Koeln", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t45", title: "Unterbringung Lehrpersonal Koeln", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t46", title: "An-/Abreise alle koordinieren (Koeln)", category: "koeln", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t47", title: "Aufbauhelfer:innen koordinieren", category: "koeln", who: [], dueDate: "November", status: "Offen", priority: "Normal", notes: "" },
  { id: "t48", title: "Verpflegung Aufbautage organisieren", category: "koeln", who: [], dueDate: "November", status: "Offen", priority: "Normal", notes: "" },
  { id: "t49", title: "CPDP-Pass Studierende anfragen (Ferre/Therrie)", category: "cpdp", who: ["Laura Därr"], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "Wie bekommen Studis ihren Pass?" },
  { id: "t50", title: "CPDP-Anmeldung Lehrende (Joel, Laura, Elko)", category: "cpdp", who: ["Laura Därr"], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t51", title: "Kosten Panel CPDP bezahlen", category: "cpdp", who: [], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t52", title: "Speaker-Info Panel ausfuellen", category: "cpdp", who: ["Laura Därr"], dueDate: "April", status: "Offen", priority: "Normal", notes: "Zeitslot 20. Mai 11:50–13:05 bestaetigt" },
  { id: "t53", title: "Judith anfragen", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t54", title: "Geeske anfragen", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t55", title: "Konzept Ferre", category: "cpdp", who: ["Joel Baumann"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t56", title: "Zoomtermin finden (Geeske, Joel, Judith, Laura + Studi)", category: "cpdp", who: ["Laura Därr"], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t57", title: "Inhaltliche Planung Slot ausarbeiten", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t58", title: "Praesentation und Materialien vorbereiten", category: "cpdp", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t59", title: "Abstract Panel", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t60", title: "Submission Panel", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t61", title: "Contract Panel", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t62", title: "Infos fuer Programm und Publikation bereitgestellt", category: "cpdp", who: ["Laura Därr"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t63", title: "Folien / Beitraege der Peers einsammeln", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t64", title: "Praesentation finalisieren", category: "cpdp", who: [], dueDate: "Anfang Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t65", title: "Raumplan Jan van Damme (Wintergarten) anfragen", category: "cpdp", who: ["Joel Baumann", "Laura Därr"], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "Masse anfragen" },
  { id: "t66", title: "Raumplan in Miro teilen", category: "cpdp", who: ["Leonie"], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t67", title: "3D-Modell Wintergarten erstellen", category: "cpdp", who: [], dueDate: "April/Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t68", title: "Kuration abstimmen: Brainrot, Einzelarbeiten, Geeske, Judith, Ueberwachungskamera?", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "Bei Ueberwachungskamera: Konzepttext noetig" },
  { id: "t69", title: "Kurationstext / Konzept fuer Einreichung schreiben", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "Nur wenn Ueberwachungskamera Teil der Kuration" },
  { id: "t70", title: "Haenge-/Installationsplan Wintergarten", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t71", title: "Tech Rider Bruessel erstellen", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t72", title: "Aufbau koordinieren: 17./18. Mai", category: "cpdp", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t73", title: "Abbau 23. Mai koordinieren", category: "cpdp", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t74", title: "Konzept", category: "cpdp", who: ["Elko"], dueDate: "", status: "Erledigt", priority: "Normal", notes: "" },
  { id: "t75", title: "Radiobeitrag produzieren", category: "cpdp", who: ["Laura Därr", "Joel Baumann", "Jessie", "Lisa Mühl", "Fabian", "Bob", "Elko"], dueDate: "April/Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t76", title: "Interview vor Ort Jessi und Lisa planen (Technik, Ort, Zeit)", category: "cpdp", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t77", title: "Snippets aus Interview schneiden (fuer Ankuendigung)", category: "cpdp", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t78", title: "Radiobeitrag finalisieren und veroeffentlichen", category: "cpdp", who: [], dueDate: "vor CPDP", status: "Offen", priority: "Normal", notes: "" },
  { id: "t79", title: "Buchformat festlegen: Hardcover / Softcover, Bindung, Masse, Sprache (DE / EN / zweispr.)", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t80", title: "Inhaltsstruktur / Kapitelgliederung entwickeln", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t81", title: "Forschungsgebiete und Kernthesen definieren (was kommt rein?)", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t82", title: "Kurzbeschreibung ca. 2.000 Zeichen schreiben", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t83", title: "Autorinnen-Liste und Aufgabenverteilung festlegen", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t84", title: "Druckerei anfragen und Angebote einholen", category: "pub", who: [], dueDate: "April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t85", title: "ISBN beantragen (falls gewuenscht)", category: "pub", who: [], dueDate: "Mai", status: "Offen", priority: "Normal", notes: "" },
  { id: "t86", title: "Google Drive Ordner anlegen (Texte / Bilder / Grafiken / Rohfassungen / Reinzeichnung / Druckdaten)", category: "pub", who: [], dueDate: "sofort \u2014 April", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t87", title: "Beitraege Studierende einsammeln (Deadline setzen!)", category: "pub", who: [], dueDate: "September", status: "Offen", priority: "Normal", notes: "" },
  { id: "t88", title: "Beitraege Peers einsammeln (Geeske, Judith, Joel, Elko u.a.)", category: "pub", who: [], dueDate: "September", status: "Offen", priority: "Normal", notes: "" },
  { id: "t89", title: "Bildmaterial sammeln: Artworks, Installationsfotos, Portraets", category: "pub", who: [], dueDate: "laufend", status: "Offen", priority: "Normal", notes: "" },
  { id: "t90", title: "Ausstellungsfotos (professionell) beauftragen", category: "pub", who: [], dueDate: "Mai + Dez.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t91", title: "Kuratorischen Text schreiben", category: "pub", who: ["Laura Därr", "Joel Baumann"], dueDate: "September", status: "Offen", priority: "Normal", notes: "" },
  { id: "t92", title: "Impressum, Foerderhinweise, Danksagungen zusammenstellen", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t93", title: "Website-Beitraege und Blogposts aus Forschung erstellen", category: "pub", who: [], dueDate: "laufend", status: "Offen", priority: "Normal", notes: "" },
  { id: "t94", title: "Alle Texte gegenlesen und vereinheitlichen (Stil, Laenge, Formatvorgaben)", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t95", title: "Lektorat: Rechtschreibung, Grammatik (intern oder extern?)", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t96", title: "Uebersetzungen pruefen / anfertigen (falls zweisprachig)", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t97", title: "1. Korrekturrunde an Autorinnen zuruecksenden", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t98", title: "Korrekturen einarbeiten — Deadline fuer Aenderungen setzen!", category: "pub", who: [], dueDate: "Ende Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t99", title: "Layoutkonzept und Raster entwickeln — wer macht das Layout?", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t100", title: "Cover-Gestaltung", category: "pub", who: [], dueDate: "Oktober", status: "Offen", priority: "Normal", notes: "" },
  { id: "t101", title: "Innenteil setzen: Texte und Bilder einpflegen", category: "pub", who: [], dueDate: "Oktober / Nov.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t102", title: "Probeausdruck / PDF zur internen Ansicht", category: "pub", who: [], dueDate: "November", status: "Offen", priority: "Normal", notes: "" },
  { id: "t103", title: "2. Korrekturrunde Layout — alle Beteiligten", category: "pub", who: [], dueDate: "November", status: "Offen", priority: "Normal", notes: "" },
  { id: "t104", title: "Finales Okay einholen", category: "pub", who: [], dueDate: "Anfang Nov.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t105", title: "Reinzeichnung: Druckdaten erstellen (PDF/X-3, CMYK, 3mm Anschnitt, 300 dpi)", category: "pub", who: [], dueDate: "Anfang Nov.", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t106", title: "Druckdaten an Druckerei uebermitteln und Freigabe erteilen", category: "pub", who: [], dueDate: "Anfang Nov.", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t107", title: "Andruckpruefung durchfuehren", category: "pub", who: [], dueDate: "Mitte Nov.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t108", title: "Lieferdatum bestaetigen", category: "pub", who: [], dueDate: "Mitte Nov.", status: "Offen", priority: "Dringend", notes: "" },
  { id: "t109", title: "PDF-Version fuer Website und Download aufbereiten", category: "pub", who: [], dueDate: "11. Dez.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t110", title: "Publikation auf Website veroeffentlichen und verlinken", category: "pub", who: [], dueDate: "11. Dez.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t111", title: "Exemplare an Peers, Foerderinnen, Presse versenden", category: "pub", who: [], dueDate: "ab 11. Dez.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t112", title: "Archivexemplare fuer KHK / Bibliothek", category: "pub", who: [], dueDate: "ab 11. Dez.", status: "Offen", priority: "Normal", notes: "" },
  { id: "t113", title: "Pressetext schreiben (DE + EN)", category: "pr", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t114", title: "Pressetermine festlegen und Pressemappe zusammenstellen", category: "pr", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t115", title: "Presseverteiler aufbauen / aktualisieren", category: "pr", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t116", title: "Korrekturen Save the Date einarbeiten und versenden", category: "pr", who: [], dueDate: "sofort \u2014 April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t117", title: "Timetable Presse erstellen", category: "pr", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t118", title: "Entscheidung: eigene Website-Seite oder Unterseite Projektseite?", category: "pr", who: [], dueDate: "sofort \u2014 April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t119", title: "Website-Texte Sentiment korrigieren und aktualisieren", category: "pr", who: [], dueDate: "April", status: "Offen", priority: "Normal", notes: "" },
  { id: "t120", title: "Presseberichte verfolgen, auswerten, archivieren", category: "pr", who: [], dueDate: "laufend", status: "Offen", priority: "Normal", notes: "" },
  { id: "t121", title: "waehrend Ausstellung", category: "pr", who: [], dueDate: "Post", status: "Offen", priority: "Normal", notes: "" },
  { id: "t122", title: "vor Finissage", category: "pr", who: [], dueDate: "Post", status: "Offen", priority: "Normal", notes: "" },
  { id: "t123", title: "nach Finissage", category: "pr", who: [], dueDate: "Post", status: "Offen", priority: "Normal", notes: "" },
];